######  Ejemplo de Yml. Modificar para adaptarse a los test de los módulos.

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
stages:
  - UnitTest
  - Deploy


################################################################################################################
#IP Core: core
################################################################################################################

core-test-job:
  stage: UnitTest
  script:
    - cd tb
    - ./test.sh
  artifacts:
   expire_in: 2 days
   paths:
    - ./tb/core_html/*
  tags:
    - ghdl
Doc-job:
  stage: UnitTest
  script:
    - cd ./lib/doc-gen
    - doxygen Doxyfile
  artifacts:
    expire_in: 2 days
    paths:
      - ./doc/gen/*
  tags:
    - doxygen
########################################

core-checkStyle-job:
  stage: UnitTest
  script:
    - cd src
    - echo $(*.vhd)
  tags:
    - ghdl-0.36dev

########################################
core-deploy:
  stage: Deploy
  script:
    - cd ./
    - npm install .
    - npm publish
  tags:
    - ghdl
  only:
    - master
